export type CuisineSeed = {
  id: string;
  title: string;
  imageKey: string;
  names: readonly string[];
  dishes: readonly string[];
  description: string;
  dietary: "vegetarian" | "vegan" | "mixed";
  priceIN: number;
};

// Original editorial seeds. Branches and menus are generated, never scraped.
export const cuisines: CuisineSeed[] = [
  {
    id: "north-indian",
    title: "North Indian",
    imageKey: "indian",
    names: [
      "Saffron Table",
      "Copper Courtyard",
      "The Warm Tawa",
      "Cumin House",
    ],
    dishes: [
      "Paneer makhani",
      "Dal tadka",
      "Smoked aubergine",
      "Chole masala",
      "Jeera rice",
      "Butter naan",
      "Tandoori chicken",
      "Palak paneer",
    ],
    description:
      "Slow-cooked gravies, fragrant spices and breads from the tandoor.",
    dietary: "mixed",
    priceIN: 240,
  },
  {
    id: "south-indian",
    title: "South Indian",
    imageKey: "dosa",
    names: [
      "Morning Tiffin",
      "Curry Leaf Corner",
      "Steam & Stone",
      "The Dosa Room",
    ],
    dishes: [
      "Masala dosa",
      "Ghee podi idli",
      "Medu vada",
      "Onion uttapam",
      "Lemon rice",
      "Rava dosa",
      "Sambar rice",
      "Coconut chutney set",
    ],
    description: "Crisp dosas, steamed tiffin and freshly ground chutneys.",
    dietary: "vegetarian",
    priceIN: 150,
  },
  {
    id: "gujarati",
    title: "Gujarati",
    imageKey: "indian",
    names: [
      "The Brass Thali",
      "Sesame Courtyard",
      "Gentle Spice",
      "Supper at Seven",
    ],
    dishes: [
      "Khaman dhokla",
      "Undhiyu",
      "Thepla set",
      "Gujarati kadhi",
      "Dal dhokli",
      "Handvo",
      "Sev tameta",
      "Methi muthia",
    ],
    description:
      "Balanced home-style plates with seasonal vegetables and gentle spice.",
    dietary: "vegetarian",
    priceIN: 190,
  },
  {
    id: "punjabi",
    title: "Punjabi",
    imageKey: "indian",
    names: [
      "Tandoor Lane",
      "Butter & Bread",
      "The Copper Pot",
      "Golden Griddle",
    ],
    dishes: [
      "Dal makhani",
      "Chole kulcha",
      "Paneer tikka",
      "Amritsari fish",
      "Rajma rice",
      "Aloo paratha",
      "Sarson saag",
      "Chicken tikka",
    ],
    description:
      "Hearty tandoor favourites, slow-simmered dal and warm breads.",
    dietary: "mixed",
    priceIN: 250,
  },
  {
    id: "mughlai",
    title: "Mughlai",
    imageKey: "indian",
    names: ["Saffron Hearth", "Silk & Spice", "The Covered Pot", "Evening Dum"],
    dishes: [
      "Chicken korma",
      "Vegetable dum pulao",
      "Mushroom kebab",
      "Paneer pasanda",
      "Seekh kebab",
      "Shahi dal",
      "Rumali roti",
      "Saffron phirni",
    ],
    description:
      "Aromatic slow-cooked dishes with layered spices and delicate textures.",
    dietary: "mixed",
    priceIN: 290,
  },
  {
    id: "bengali",
    title: "Bengali",
    imageKey: "indian",
    names: [
      "Mustard & Rice",
      "Riverbank Kitchen",
      "Five Spice Table",
      "The Clay Bowl",
    ],
    dishes: [
      "Shukto",
      "Aloo posto",
      "Cholar dal",
      "Fish paturi",
      "Luchi aloo dum",
      "Vegetable chop",
      "Bengali pulao",
      "Mishti doi",
    ],
    description:
      "Mustard, poppy seed and warm five-spice notes across a thoughtful menu.",
    dietary: "mixed",
    priceIN: 220,
  },
  {
    id: "maharashtrian",
    title: "Maharashtrian",
    imageKey: "indian",
    names: [
      "The Millet Kitchen",
      "Coconut & Chilli",
      "Supper Ghar",
      "Tamarind Tiffin",
    ],
    dishes: [
      "Misal pav",
      "Kanda poha",
      "Sabudana khichdi",
      "Pithla bhakri",
      "Bharli vangi",
      "Thalipeeth",
      "Kothimbir vadi",
      "Puran poli",
    ],
    description:
      "Comforting grains, bright chutneys and a generous hand with coriander.",
    dietary: "vegetarian",
    priceIN: 170,
  },
  {
    id: "rajasthani",
    title: "Rajasthani",
    imageKey: "indian",
    names: [
      "The Sandstone Table",
      "Bajra & Ghee",
      "Desert Hearth",
      "Three Bowls",
    ],
    dishes: [
      "Dal baati churma",
      "Gatte ki sabzi",
      "Ker sangri",
      "Bajra roti set",
      "Panchmel dal",
      "Papad ki sabzi",
      "Onion kachori",
      "Ghevar",
    ],
    description:
      "Regional grain dishes and slow-cooked classics served with care.",
    dietary: "vegetarian",
    priceIN: 230,
  },
  {
    id: "kerala",
    title: "Kerala",
    imageKey: "indian",
    names: [
      "Pepper Coast",
      "Coconut Grove Kitchen",
      "The Appam House",
      "Coastal Leaf",
    ],
    dishes: [
      "Appam with stew",
      "Vegetable avial",
      "Puttu kadala",
      "Malabar parotta",
      "Fish moilee",
      "Pumpkin erissery",
      "Cabbage thoran",
      "Payasam",
    ],
    description:
      "Coconut, pepper and curry leaf bring depth to coastal plates.",
    dietary: "mixed",
    priceIN: 230,
  },
  {
    id: "street-food",
    title: "Street food",
    imageKey: "indian",
    names: [
      "Corner Counter",
      "The Evening Cart",
      "Small Plate Street",
      "Snack Junction",
    ],
    dishes: [
      "Pav bhaji",
      "Vada pav",
      "Aloo tikki",
      "Paneer kathi roll",
      "Corn chaat",
      "Samosa pair",
      "Chilli toast",
      "Masala fries",
    ],
    description: "Freshly made small plates, tangy sauces and crisp textures.",
    dietary: "vegetarian",
    priceIN: 130,
  },
  {
    id: "biryani",
    title: "Biryani",
    imageKey: "biryani",
    names: [
      "Dum & Grain",
      "The Saffron Pot",
      "Long Grain Kitchen",
      "Layered Spice",
    ],
    dishes: [
      "Vegetable dum biryani",
      "Chicken dum biryani",
      "Paneer biryani",
      "Mushroom biryani",
      "Egg biryani",
      "Pepper chicken rice",
      "Saffron pulao",
      "Cucumber raita",
    ],
    description:
      "Long-grain rice, fragrant whole spices and a patient dum finish.",
    dietary: "mixed",
    priceIN: 280,
  },
  {
    id: "dosa",
    title: "Dosa",
    imageKey: "dosa",
    names: [
      "The Crisp Edge",
      "Dosa Daily",
      "Batter & Stone",
      "The Tiffin Window",
    ],
    dishes: [
      "Classic masala dosa",
      "Mysore masala dosa",
      "Ghee roast dosa",
      "Rava onion dosa",
      "Set dosa",
      "Podi dosa",
      "Paneer dosa",
      "Mini idli bowl",
    ],
    description:
      "Golden edges, soft centres and chutneys ground every morning.",
    dietary: "vegetarian",
    priceIN: 160,
  },
  {
    id: "thali",
    title: "Thali",
    imageKey: "indian",
    names: [
      "Full Circle Kitchen",
      "A Little of Everything",
      "The Lunch Plate",
      "Everyday Thali",
    ],
    dishes: [
      "Garden thali",
      "Dal and roti thali",
      "Seasonal vegetable thali",
      "Paneer lunch plate",
      "Rice and curry thali",
      "Mini lunch thali",
      "Weekend feast",
      "Millet thali",
    ],
    description:
      "A complete plate of changing vegetables, dal, grains and bread.",
    dietary: "vegetarian",
    priceIN: 260,
  },
  {
    id: "chaat",
    title: "Chaat",
    imageKey: "indian",
    names: [
      "Tamarind Counter",
      "Crisp & Tangy",
      "Chaat Hour",
      "The Little Katori",
    ],
    dishes: [
      "Dahi puri",
      "Bhel puri",
      "Papdi chaat",
      "Aloo tikki chaat",
      "Sev puri",
      "Raj kachori",
      "Samosa chaat",
      "Corn bhel",
    ],
    description: "Crunch, tang and cooling yoghurt in bright little plates.",
    dietary: "vegetarian",
    priceIN: 120,
  },
  {
    id: "pizza",
    title: "Pizza",
    imageKey: "pizza",
    names: [
      "Ember Slice",
      "Roundhouse Pizza",
      "Dough & Fire",
      "The Tomato Room",
    ],
    dishes: [
      "Margherita",
      "Roasted mushroom pizza",
      "Garden pesto pizza",
      "Pepperoni pizza",
      "Four cheese pizza",
      "Chilli honey pizza",
      "Garlic focaccia",
      "Tomato burrata salad",
    ],
    description:
      "Slow-fermented dough, a hot oven and thoughtfully chosen toppings.",
    dietary: "mixed",
    priceIN: 340,
  },
  {
    id: "burgers",
    title: "Burgers",
    imageKey: "burger",
    names: ["Stack & Pickle", "The Bun House", "Smash Corner", "Good Griddle"],
    dishes: [
      "Classic cheeseburger",
      "Crispy chicken burger",
      "Mushroom melt",
      "Black bean burger",
      "Double stack",
      "Chilli crunch burger",
      "House fries",
      "Pickle slaw",
    ],
    description: "Toasted buns, crisp pickles and griddle-seared favourites.",
    dietary: "mixed",
    priceIN: 230,
  },
  {
    id: "sushi",
    title: "Sushi",
    imageKey: "sushi",
    names: ["Rice Paper Table", "Nori Room", "The Quiet Roll", "Sesame Tide"],
    dishes: [
      "Avocado maki",
      "Cucumber maki",
      "Salmon roll",
      "Crispy tofu roll",
      "Prawn tempura roll",
      "Vegetable nigiri",
      "Edamame",
      "Seaweed salad",
    ],
    description:
      "Carefully rolled rice, fresh fillings and balanced seasoning.",
    dietary: "mixed",
    priceIN: 390,
  },
  {
    id: "ramen",
    title: "Ramen",
    imageKey: "noodles",
    names: ["Nami Kitchen", "Broth & Bowl", "The Noodle Room", "Steam House"],
    dishes: [
      "Miso mushroom ramen",
      "Shoyu chicken ramen",
      "Chilli sesame ramen",
      "Tofu tantanmen",
      "Garlic broth noodles",
      "Vegetable gyoza",
      "Soy-marinated egg",
      "Cucumber sunomono",
    ],
    description: "Deep broths, springy noodles and carefully layered toppings.",
    dietary: "mixed",
    priceIN: 330,
  },
  {
    id: "korean",
    title: "Korean",
    imageKey: "noodles",
    names: [
      "Sesame Seoul Table",
      "Gochu Kitchen",
      "The Rice Pan",
      "Stone Bowl House",
    ],
    dishes: [
      "Vegetable bibimbap",
      "Tofu bibimbap",
      "Japchae",
      "Kimchi fried rice",
      "Crispy chicken bites",
      "Scallion pancake",
      "Tteokbokki",
      "Sesame cucumber",
    ],
    description:
      "Warm rice bowls, crisp vegetables and fermented chilli depth.",
    dietary: "mixed",
    priceIN: 310,
  },
  {
    id: "thai",
    title: "Thai",
    imageKey: "noodles",
    names: [
      "Lime & Lemongrass",
      "Basil House",
      "The Coconut Spoon",
      "Green Curry Table",
    ],
    dishes: [
      "Tofu pad thai",
      "Green vegetable curry",
      "Red chicken curry",
      "Basil fried rice",
      "Drunken noodles",
      "Tom kha soup",
      "Papaya salad",
      "Mango sticky rice",
    ],
    description: "Fresh herbs, lime, coconut and balanced heat.",
    dietary: "mixed",
    priceIN: 290,
  },
  {
    id: "chinese",
    title: "Chinese",
    imageKey: "noodles",
    names: [
      "Wok & Willow",
      "Ginger Kitchen",
      "The Dumpling Room",
      "Eight Bowls",
    ],
    dishes: [
      "Vegetable hakka noodles",
      "Chilli paneer",
      "Garlic fried rice",
      "Kung pao tofu",
      "Chicken dumplings",
      "Vegetable spring rolls",
      "Hot and sour soup",
      "Sesame greens",
    ],
    description: "Wok-tossed favourites and hand-folded dumplings.",
    dietary: "mixed",
    priceIN: 240,
  },
  {
    id: "mexican",
    title: "Mexican",
    imageKey: "salad",
    names: [
      "Lime Mesa",
      "The Corn Kitchen",
      "Roasted Pepper",
      "Tortilla Table",
    ],
    dishes: [
      "Roasted vegetable tacos",
      "Chicken burrito",
      "Black bean bowl",
      "Mushroom quesadilla",
      "Corn elote",
      "Guacamole and chips",
      "Salsa rice",
      "Cinnamon churros",
    ],
    description: "Corn tortillas, bright salsa and slow-cooked fillings.",
    dietary: "mixed",
    priceIN: 270,
  },
  {
    id: "mediterranean",
    title: "Mediterranean",
    imageKey: "salad",
    names: [
      "Olive & Grain",
      "The Mezze Table",
      "Sunlit Kitchen",
      "Lemon Grove",
    ],
    dishes: [
      "Falafel plate",
      "Hummus and pita",
      "Chicken shawarma",
      "Roasted aubergine bowl",
      "Tabbouleh",
      "Feta salad",
      "Lentil soup",
      "Tahini brownie",
    ],
    description:
      "Olive oil, fresh herbs, warm flatbreads and generous vegetables.",
    dietary: "mixed",
    priceIN: 300,
  },
  {
    id: "italian",
    title: "Italian",
    imageKey: "pizza",
    names: [
      "Basil & Flour",
      "Pasta Parlour",
      "The Sunday Sauce",
      "Little Terracotta",
    ],
    dishes: [
      "Tomato basil penne",
      "Mushroom cream pasta",
      "Spinach ravioli",
      "Pesto spaghetti",
      "Chicken lasagne",
      "Bruschetta",
      "Caprese salad",
      "Tiramisu",
    ],
    description: "Good pasta, slow sauces and simple seasonal ingredients.",
    dietary: "mixed",
    priceIN: 330,
  },
  {
    id: "bakery",
    title: "Bakery",
    imageKey: "bakery",
    names: [
      "Daylight Deli",
      "The Proofing Room",
      "Crumb & Butter",
      "Morning Loaf",
    ],
    dishes: [
      "Butter croissant",
      "Almond croissant",
      "Sourdough loaf",
      "Cinnamon bun",
      "Cheese twist",
      "Banana bread",
      "Chocolate muffin",
      "Seeded roll",
    ],
    description: "Small-batch breads and pastries with golden, flaky edges.",
    dietary: "vegetarian",
    priceIN: 160,
  },
  {
    id: "desserts",
    title: "Desserts",
    imageKey: "dessert",
    names: ["Little Parlour", "The Cocoa Spoon", "Soft Centre", "Last Course"],
    dishes: [
      "Cloud tiramisu",
      "Chocolate fondant",
      "Vanilla cheesecake",
      "Lemon tart",
      "Salted caramel brownie",
      "Strawberry shortcake",
      "Pistachio pudding",
      "Dark chocolate mousse",
    ],
    description:
      "Thoughtful sweet finishes, rich chocolate and seasonal fruit.",
    dietary: "vegetarian",
    priceIN: 210,
  },
  {
    id: "coffee",
    title: "Coffee",
    imageKey: "coffee",
    names: [
      "First Light Coffee",
      "The Daily Pour",
      "Quiet Cup",
      "Filter & Field",
    ],
    dishes: [
      "Flat white",
      "Cappuccino",
      "Iced latte",
      "Filter coffee",
      "Cold brew",
      "Mocha",
      "Oat latte",
      "Hot chocolate",
    ],
    description: "Carefully brewed coffee for a pause in your day.",
    dietary: "vegetarian",
    priceIN: 170,
  },
  {
    id: "healthy",
    title: "Healthy",
    imageKey: "salad",
    names: ["Ember & Grain", "Green Table", "Good Bowl", "The Garden Plate"],
    dishes: [
      "Charred garden bowl",
      "Quinoa crunch salad",
      "Roasted chickpea bowl",
      "Grilled chicken salad",
      "Tofu greens bowl",
      "Lentil and beet salad",
      "Avocado toast",
      "Seasonal fruit cup",
    ],
    description:
      "Colourful vegetables, satisfying grains and bright dressings.",
    dietary: "mixed",
    priceIN: 290,
  },
  {
    id: "vegan",
    title: "Vegan",
    imageKey: "salad",
    names: [
      "Plant & Plate",
      "Kind Kitchen",
      "The Sprout Room",
      "Leaf & Lentil",
    ],
    dishes: [
      "Miso tofu bowl",
      "Chickpea curry",
      "Mushroom shawarma",
      "Black bean tacos",
      "Cashew pesto pasta",
      "Roasted cauliflower",
      "Coconut chia pudding",
      "Lentil burger",
    ],
    description: "Plant-based plates built around flavour and texture.",
    dietary: "vegan",
    priceIN: 270,
  },
  {
    id: "breakfast",
    title: "Breakfast",
    imageKey: "bakery",
    names: [
      "Morning Table",
      "The Early Plate",
      "Rise Kitchen",
      "Breakfast Clubhouse",
    ],
    dishes: [
      "Avocado toast",
      "Scrambled eggs on sourdough",
      "Berry pancakes",
      "Granola yoghurt bowl",
      "Masala omelette",
      "French toast",
      "Breakfast potatoes",
      "Fruit and oat bowl",
    ],
    description: "A generous start with familiar breakfast favourites.",
    dietary: "vegetarian",
    priceIN: 200,
  },
  {
    id: "sandwiches",
    title: "Sandwiches",
    imageKey: "burger",
    names: [
      "Between Slices",
      "The Lunch Deli",
      "Sourdough Counter",
      "Toast & Pickle",
    ],
    dishes: [
      "Daylight club",
      "Roast vegetable sandwich",
      "Chicken pesto sandwich",
      "Cheese toastie",
      "Mushroom melt",
      "Falafel wrap",
      "Egg salad sandwich",
      "Tomato mozzarella baguette",
    ],
    description: "Freshly built sandwiches, crisp leaves and house dressings.",
    dietary: "mixed",
    priceIN: 210,
  },
];

export const groceryCategories = [
  {
    id: "produce",
    title: "Fruit & vegetables",
    imageKey: "produce",
    products: [
      "Avocados · 2 pack",
      "Vine tomatoes · 500 g",
      "Carrots · 500 g",
      "Seasonal apples · 4 pack",
      "Baby spinach · 150 g",
      "Lemons · 4 pack",
      "Bananas · 6 pack",
      "Broccoli · 1 head",
    ],
  },
  {
    id: "dairy",
    title: "Dairy & eggs",
    imageKey: "groceries",
    products: [
      "Whole milk · 1 L",
      "Oat drink · 1 L",
      "Natural yoghurt · 400 g",
      "Free-range eggs · 6 pack",
      "Salted butter · 200 g",
      "Cheddar · 200 g",
      "Paneer · 200 g",
      "Greek yoghurt · 450 g",
    ],
  },
  {
    id: "beverages",
    title: "Beverages",
    imageKey: "coffee",
    products: [
      "Sparkling water · 6 pack",
      "Orange juice · 1 L",
      "Ground coffee · 250 g",
      "Breakfast tea · 40 bags",
      "Coconut water · 1 L",
      "Apple juice · 1 L",
      "Herbal tea · 20 bags",
      "Still water · 1.5 L",
    ],
  },
  {
    id: "snacks",
    title: "Snacks",
    imageKey: "groceries",
    products: [
      "Sea-salt popcorn · 100 g",
      "Dark chocolate · 100 g",
      "Roasted almonds · 150 g",
      "Potato crisps · 150 g",
      "Oat biscuits · 200 g",
      "Trail mix · 200 g",
      "Rice crackers · 100 g",
      "Peanut butter · 340 g",
    ],
  },
  {
    id: "bakery",
    title: "Bakery",
    imageKey: "bakery",
    products: [
      "Sourdough loaf · 600 g",
      "Butter croissants · 4 pack",
      "Wholegrain bread · 400 g",
      "Bagels · 4 pack",
      "Pita bread · 6 pack",
      "Cinnamon buns · 2 pack",
      "Soft rolls · 6 pack",
      "Flatbreads · 4 pack",
    ],
  },
  {
    id: "household",
    title: "Household",
    imageKey: "household",
    products: [
      "Dish soap · 500 ml",
      "Kitchen towels · 2 rolls",
      "Laundry liquid · 1 L",
      "Bin liners · 20 pack",
      "Surface cleaner · 500 ml",
      "Sponges · 4 pack",
      "Tissues · 100 pack",
      "Baking paper · 10 m",
    ],
  },
  {
    id: "personal-care",
    title: "Personal care",
    imageKey: "household",
    products: [
      "Hand wash · 250 ml",
      "Toothpaste · 100 g",
      "Shampoo · 250 ml",
      "Body wash · 300 ml",
      "Cotton pads · 80 pack",
      "Lip balm · 1 pack",
      "Hand cream · 75 ml",
      "Soap bars · 3 pack",
    ],
  },
  {
    id: "instant",
    title: "Quick meals",
    imageKey: "groceries",
    products: [
      "Rice noodles · 250 g",
      "Tomato soup · 400 g",
      "Vegetable noodles · 4 pack",
      "Ready rice · 250 g",
      "Pasta sauce · 350 g",
      "Couscous · 500 g",
      "Lentil soup · 400 g",
      "Flatbread kit · 1 pack",
    ],
  },
  {
    id: "frozen",
    title: "Frozen",
    imageKey: "groceries",
    products: [
      "Garden peas · 500 g",
      "Mixed berries · 400 g",
      "Vegetable dumplings · 300 g",
      "Vanilla ice cream · 500 ml",
      "Sweetcorn · 500 g",
      "Oven chips · 750 g",
      "Spinach portions · 500 g",
      "Mango pieces · 400 g",
    ],
  },
  {
    id: "essentials",
    title: "Essentials",
    imageKey: "groceries",
    products: [
      "Basmati rice · 1 kg",
      "Penne pasta · 500 g",
      "Chickpeas · 400 g",
      "Chopped tomatoes · 400 g",
      "Olive oil · 500 ml",
      "Rolled oats · 500 g",
      "Red lentils · 500 g",
      "Plain flour · 1 kg",
    ],
  },
] as const;
