const target = (id, query, tags, type, notes, scope = "exact") => ({
  id,
  query,
  tags,
  type,
  orientation: "landscape",
  scope,
  ...(notes ? { notes } : {}),
});

const groups = {
  food: [
    [
      "paneer-curry",
      "Indian paneer curry restaurant food",
      ["paneer curry", "paneer", "curry", "north indian", "vegetarian"],
    ],
    [
      "dal-lentils",
      "Indian dal tadka lentil curry food",
      ["dal", "lentils", "curry", "indian", "vegetarian"],
    ],
    [
      "naan-flatbread",
      "Indian butter naan flatbread food",
      ["naan", "flatbread", "bread", "indian"],
    ],
    [
      "biryani",
      "Indian biryani rice restaurant food",
      ["biryani", "rice", "indian"],
    ],
    ["dosa", "South Indian dosa food", ["dosa", "south indian", "crepe"]],
    [
      "idli",
      "South Indian idli breakfast food",
      ["idli", "south indian", "breakfast"],
    ],
    ["vada", "South Indian medu vada food", ["vada", "south indian", "snack"]],
    ["chaat", "Indian chaat street food", ["chaat", "street food", "indian"]],
    ["samosa", "Indian samosa food plate", ["samosa", "street food", "indian"]],
    [
      "tandoori-chicken",
      "Indian tandoori chicken restaurant food",
      ["tandoori chicken", "chicken", "indian", "grilled"],
    ],
    [
      "butter-chicken",
      "Indian butter chicken curry restaurant",
      ["butter chicken", "chicken", "curry", "indian"],
    ],
    [
      "palak-paneer",
      "Indian palak paneer curry",
      ["palak paneer", "paneer", "spinach", "curry", "indian"],
    ],
    [
      "chole",
      "Indian chole chickpea curry",
      ["chole", "chickpeas", "curry", "indian", "vegetarian"],
    ],
    [
      "rajma",
      "Indian rajma kidney bean curry",
      ["rajma", "beans", "curry", "indian", "vegetarian"],
    ],
    ["thali", "Indian thali meal platter", ["thali", "indian", "platter"]],
    [
      "indian-snacks-assortment",
      "Indian pakora snack plate",
      ["street food", "chaat", "indian"],
      "Category fallback; representative Indian snack assortment.",
      "generic",
    ],
    ["poha", "Indian poha breakfast", ["poha", "breakfast", "indian"]],
    [
      "pav-bhaji",
      "Indian pav bhaji street food",
      ["pav bhaji", "street food", "indian"],
    ],
    [
      "fish-curry",
      "Indian fish curry restaurant food",
      ["fish curry", "fish", "curry", "indian"],
    ],
    [
      "south-indian-breakfast",
      "South Indian uttapam breakfast food",
      ["south indian", "breakfast"],
      "Category fallback; representative South Indian breakfast.",
      "generic",
    ],
    [
      "kebab",
      "Indian seekh kebab plate",
      ["kebab", "mughlai", "indian", "grilled"],
    ],
    [
      "kathi-roll",
      "Indian kathi roll wrap close up food",
      ["kathi roll", "wrap", "street food", "indian"],
    ],
    [
      "gulab-jamun",
      "Indian gulab jamun dessert",
      ["gulab jamun", "dessert", "indian", "sweet"],
    ],
    [
      "jalebi",
      "Indian jalebi dessert",
      ["jalebi", "dessert", "indian", "sweet"],
    ],
    [
      "margherita-pizza",
      "margherita pizza restaurant food",
      ["margherita", "pizza", "italian"],
    ],
    [
      "vegetable-pizza",
      "vegetable pizza restaurant food",
      ["vegetable pizza", "pizza", "italian", "vegetarian"],
    ],
    [
      "mushroom-pizza",
      "mushroom pizza restaurant food",
      ["mushroom pizza", "pizza", "italian"],
    ],
    [
      "tomato-pasta",
      "tomato basil pasta restaurant food",
      ["tomato pasta", "pasta", "italian"],
    ],
    [
      "cream-pasta",
      "creamy pasta restaurant food",
      ["cream pasta", "pasta", "italian"],
    ],
    [
      "pesto-pasta",
      "pesto pasta restaurant food",
      ["pesto pasta", "pasta", "italian"],
    ],
    [
      "lasagna",
      "Italian lasagna restaurant food",
      ["lasagna", "pasta", "italian"],
    ],
    [
      "risotto",
      "Italian mushroom risotto food",
      ["risotto", "rice", "italian"],
    ],
    [
      "garlic-bread",
      "Italian garlic bread food",
      ["garlic bread", "bread", "italian"],
    ],
    [
      "caprese",
      "Italian caprese salad food",
      ["caprese", "salad", "italian", "vegetarian"],
    ],
    [
      "sushi-rolls",
      "Japanese sushi rolls restaurant",
      ["sushi", "rolls", "japanese"],
    ],
    [
      "salmon-sushi",
      "salmon sushi restaurant food",
      ["salmon sushi", "sushi", "japanese"],
    ],
    [
      "ramen",
      "Japanese ramen bowl restaurant food",
      ["ramen", "noodles", "japanese"],
    ],
    ["udon", "Japanese udon noodle bowl", ["udon", "noodles", "japanese"]],
    ["bibimbap", "Korean bibimbap food bowl", ["bibimbap", "rice", "korean"]],
    [
      "korean-chicken",
      "Korean fried chicken food",
      ["fried chicken", "chicken", "korean"],
    ],
    [
      "kimchi-stew",
      "Korean kimchi stew food",
      ["kimchi stew", "stew", "korean"],
    ],
    [
      "fried-rice",
      "Chinese fried rice restaurant food",
      ["fried rice", "rice", "chinese"],
    ],
    [
      "dumplings",
      "Asian dumplings restaurant food",
      ["dumplings", "chinese", "asian"],
    ],
    [
      "stir-fry-noodles",
      "Chinese stir fry noodles food",
      ["stir fry noodles", "noodles", "chinese"],
    ],
    [
      "thai-green-curry",
      "Thai green curry restaurant food",
      ["green curry", "curry", "thai"],
    ],
    [
      "pad-thai",
      "pad thai noodles restaurant food",
      ["pad thai", "noodles", "thai"],
    ],
    ["tom-yum", "Thai tom yum soup", ["tom yum", "soup", "thai"]],
    [
      "classic-burger",
      "classic cheeseburger restaurant food",
      ["burger", "cheeseburger", "western"],
    ],
    [
      "chicken-burger",
      "chicken burger restaurant food",
      ["chicken burger", "burger", "western"],
    ],
    [
      "veggie-burger",
      "vegetarian burger restaurant food",
      ["veggie burger", "burger", "vegetarian"],
    ],
    [
      "club-sandwich",
      "club sandwich restaurant food",
      ["club sandwich", "sandwich", "western"],
    ],
    [
      "grilled-sandwich",
      "grilled vegetable sandwich food",
      ["grilled sandwich", "sandwich", "vegetarian"],
    ],
    [
      "mediterranean-salad",
      "Mediterranean salad restaurant food",
      ["mediterranean salad", "salad", "healthy"],
    ],
    [
      "grain-bowl",
      "healthy grain bowl restaurant food",
      ["grain bowl", "healthy", "vegan"],
    ],
    [
      "avocado-toast",
      "avocado toast breakfast food",
      ["avocado toast", "breakfast", "healthy"],
    ],
    ["pancakes", "pancakes breakfast food", ["pancakes", "breakfast"]],
    [
      "omelette",
      "omelette breakfast restaurant food",
      ["omelette", "eggs", "breakfast"],
    ],
    [
      "croissant",
      "butter croissant bakery food",
      ["croissant", "bakery", "pastry"],
    ],
    [
      "sourdough",
      "artisan sourdough bread bakery",
      ["sourdough", "bread", "bakery"],
    ],
    [
      "cinnamon-roll",
      "cinnamon roll on plate bakery food",
      ["cinnamon roll", "bakery", "dessert"],
    ],
    [
      "chocolate-cake",
      "chocolate cake dessert",
      ["chocolate cake", "cake", "dessert"],
    ],
    [
      "cheesecake",
      "cheesecake dessert restaurant",
      ["cheesecake", "cake", "dessert"],
    ],
    [
      "fruit-tart",
      "fruit tart bakery dessert",
      ["fruit tart", "tart", "dessert", "bakery"],
    ],
    [
      "ice-cream",
      "artisan ice cream dessert",
      ["ice cream", "dessert", "frozen"],
    ],
    [
      "brownie",
      "chocolate brownie dessert",
      ["brownie", "chocolate", "dessert"],
    ],
    [
      "cookies",
      "fresh baked cookies dessert",
      ["cookies", "bakery", "dessert"],
    ],
    ["donuts", "artisan donuts bakery", ["donuts", "bakery", "dessert"]],
    ["espresso", "espresso coffee cafe", ["espresso", "coffee", "drink"]],
    ["latte", "latte coffee cafe", ["latte", "coffee", "drink"]],
    [
      "iced-coffee",
      "iced coffee cafe drink",
      ["iced coffee", "coffee", "drink"],
    ],
    ["tea", "black tea ceramic cup saucer plain", ["tea", "drink"]],
    [
      "smoothie",
      "fresh fruit smoothie drink",
      ["smoothie", "drink", "healthy"],
    ],
    ["lemonade", "fresh lemonade drink", ["lemonade", "drink"]],
  ],
  grocery: [
    ["avocado", "fresh avocado produce", ["avocado", "produce", "grocery"]],
    ["tomatoes", "fresh tomatoes produce", ["tomatoes", "produce", "grocery"]],
    [
      "bananas",
      "fresh bananas produce",
      ["bananas", "fruit", "produce", "grocery"],
    ],
    [
      "apples",
      "fresh apples produce",
      ["apples", "fruit", "produce", "grocery"],
    ],
    [
      "berries",
      "fresh berries produce",
      ["berries", "fruit", "produce", "grocery"],
    ],
    [
      "oranges",
      "fresh oranges produce",
      ["oranges", "fruit", "produce", "grocery"],
    ],
    [
      "leafy-greens",
      "fresh leafy greens produce",
      ["leafy greens", "vegetables", "produce", "grocery"],
    ],
    [
      "potatoes",
      "fresh potatoes produce",
      ["potatoes", "vegetables", "produce", "grocery"],
    ],
    [
      "onions",
      "fresh onions produce",
      ["onions", "vegetables", "produce", "grocery"],
    ],
    [
      "carrots",
      "fresh carrots produce",
      ["carrots", "vegetables", "produce", "grocery"],
    ],
    [
      "mushrooms",
      "fresh mushrooms produce",
      ["mushrooms", "vegetables", "produce", "grocery"],
    ],
    [
      "produce-basket",
      "fresh fruit vegetables grocery basket",
      ["fruit", "vegetables", "produce", "grocery"],
    ],
    ["milk", "glass of milk dairy close up", ["milk", "dairy", "grocery"]],
    ["yogurt", "plain yogurt bowl grocery", ["yogurt", "dairy", "grocery"]],
    ["cheese", "cheese selection grocery", ["cheese", "dairy", "grocery"]],
    ["eggs", "free range eggs carton unbranded", ["eggs", "dairy", "grocery"]],
    ["butter", "fresh butter grocery food", ["butter", "dairy", "grocery"]],
    [
      "plant-milk",
      "oat milk glass unbranded",
      ["oat milk", "plant milk", "dairy", "grocery"],
    ],
    [
      "bread-loaf",
      "fresh bread loaf bakery",
      ["bread", "loaf", "bakery", "grocery"],
    ],
    ["bagels", "fresh bagels bakery", ["bagels", "bakery", "grocery"]],
    [
      "bread-rolls",
      "fresh bread rolls bakery",
      ["rolls", "bread", "bakery", "grocery"],
    ],
    [
      "pita",
      "fresh pita flatbread",
      ["pita", "flatbread", "bakery", "grocery"],
    ],
    [
      "sparkling-water",
      "sparkling water glass bottles unbranded",
      ["sparkling water", "water", "beverages", "grocery"],
    ],
    [
      "orange-juice",
      "fresh orange juice bottle unbranded",
      ["orange juice", "juice", "beverages", "grocery"],
    ],
    [
      "apple-juice",
      "fresh apple juice glass no label",
      ["apple juice", "juice", "beverages", "grocery"],
    ],
    [
      "cola",
      "dark cola soda glass no label",
      ["cola", "soda", "beverages", "grocery"],
    ],
    [
      "tea-box",
      "loose leaf tea grocery unbranded",
      ["tea", "beverages", "grocery"],
    ],
    [
      "mixed-nuts",
      "mixed nuts snack bowl",
      ["mixed nuts", "nuts", "snacks", "grocery"],
    ],
    [
      "potato-chips",
      "potato chips snack bowl unbranded",
      ["potato chips", "chips", "snacks", "grocery"],
    ],
    ["popcorn", "popcorn snack bowl", ["popcorn", "snacks", "grocery"]],
    [
      "crackers",
      "crackers snack food unbranded",
      ["crackers", "snacks", "grocery"],
    ],
    [
      "peanut-butter",
      "peanut butter jar unbranded",
      ["peanut butter", "snacks", "grocery"],
    ],
    [
      "dish-soap",
      "dish soap bottle unbranded kitchen",
      ["dish soap", "household", "cleaning", "grocery"],
    ],
    [
      "laundry",
      "laundry liquid bottle unbranded",
      ["laundry", "household", "cleaning", "grocery"],
    ],
    [
      "kitchen-towels",
      "paper kitchen towels unbranded",
      ["kitchen towels", "household", "grocery"],
    ],
    [
      "cleaning-sponges",
      "cleaning sponges kitchen",
      ["sponges", "household", "cleaning", "grocery"],
    ],
    [
      "tissues",
      "white paper tissue box no label",
      ["tissues", "household", "grocery"],
    ],
    [
      "surface-cleaner",
      "surface cleaner bottle unbranded",
      ["surface cleaner", "household", "cleaning", "grocery"],
    ],
    [
      "hand-wash",
      "hand wash dispenser unbranded",
      ["hand wash", "personal care", "grocery"],
    ],
    [
      "toothpaste",
      "toothpaste toothbrush unbranded",
      ["toothpaste", "personal care", "grocery"],
    ],
    [
      "shampoo",
      "shampoo bottle unbranded",
      ["shampoo", "personal care", "grocery"],
    ],
    ["soap", "handmade soap bars", ["soap", "personal care", "grocery"]],
    [
      "hand-cream",
      "hand cream tube unbranded",
      ["hand cream", "personal care", "grocery"],
    ],
    [
      "rice",
      "basmati rice grains bowl",
      ["rice", "pantry", "essentials", "grocery"],
    ],
    [
      "pasta",
      "dry penne pasta grocery",
      ["pasta", "pantry", "essentials", "grocery"],
    ],
    [
      "chickpeas",
      "chickpeas bowl grocery",
      ["chickpeas", "pantry", "essentials", "grocery"],
    ],
    [
      "lentils",
      "red lentils bowl grocery",
      ["lentils", "pantry", "essentials", "grocery"],
    ],
    [
      "oats",
      "rolled oats bowl grocery",
      ["oats", "pantry", "essentials", "grocery"],
    ],
    [
      "olive-oil",
      "olive oil bottle unbranded",
      ["olive oil", "pantry", "essentials", "grocery"],
    ],
    ["frozen-peas", "frozen green peas bowl", ["peas", "frozen", "grocery"]],
    [
      "frozen-berries",
      "frozen mixed berries",
      ["berries", "frozen", "grocery"],
    ],
    [
      "dumplings",
      "frozen vegetable dumplings food",
      ["dumplings", "frozen", "grocery"],
    ],
    [
      "ice-cream",
      "vanilla ice cream tub unbranded",
      ["ice cream", "frozen", "grocery"],
    ],
    [
      "oven-chips",
      "oven french fries food",
      ["oven chips", "frozen", "grocery"],
    ],
  ],
  merchant: [
    [
      "indian-table",
      "modern Indian restaurant table food",
      ["indian", "restaurant", "merchant"],
    ],
    [
      "pizza-oven",
      "artisan pizza restaurant oven",
      ["pizza", "italian", "restaurant", "merchant"],
    ],
    [
      "sushi-counter",
      "Japanese sushi restaurant counter",
      ["sushi", "japanese", "restaurant", "merchant"],
    ],
    [
      "bakery-counter",
      "artisan bakery counter",
      ["bakery", "restaurant", "merchant"],
    ],
    [
      "coffee-counter",
      "modern coffee shop counter",
      ["coffee", "cafe", "merchant"],
    ],
    [
      "healthy-table",
      "healthy restaurant food table",
      ["healthy", "salad", "restaurant", "merchant"],
    ],
    [
      "produce-store",
      "fresh produce market display no people",
      ["produce store", "produce", "grocery", "store", "merchant"],
    ],
    [
      "grocery-shelves",
      "minimal grocery produce aisle no logos",
      ["grocery shelves", "grocery", "store", "merchant"],
    ],
  ],
};

const exactTargets = Object.entries(groups).flatMap(([type, entries]) =>
  entries.map(([id, query, tags, notes, scope]) =>
    target(
      `${type}-${id}`,
      query,
      tags,
      type,
      notes ?? "Avoid logos, text and branded packaging.",
      scope,
    ),
  ),
);

const categoryTargets = [
  target(
    "food-indian-assortment",
    "Indian food thali assortment table",
    [
      "north indian",
      "south indian",
      "gujarati",
      "punjabi",
      "mughlai",
      "bengali",
      "maharashtrian",
      "rajasthani",
      "kerala",
      "street food",
      "thali",
      "chaat",
      "indian",
    ],
    "food",
    "Category fallback; reject single-dish close-ups.",
    "generic",
  ),
  target(
    "food-mexican-assortment",
    "Mexican food assortment table",
    ["mexican"],
    "food",
    "Category fallback.",
    "generic",
  ),
  target(
    "food-mediterranean-assortment",
    "Mediterranean mezze food table",
    ["mediterranean"],
    "food",
    "Category fallback.",
    "generic",
  ),
  target(
    "food-japanese-assortment",
    "Japanese food assortment table",
    ["sushi", "ramen", "japanese"],
    "food",
    "Category fallback.",
    "generic",
  ),
  target(
    "food-korean-assortment",
    "Korean food assortment table",
    ["korean"],
    "food",
    "Category fallback.",
    "generic",
  ),
  target(
    "food-thai-assortment",
    "Thai food dishes assortment table",
    ["thai"],
    "food",
    "Category fallback.",
    "generic",
  ),
  target(
    "food-chinese-assortment",
    "Chinese food assortment table",
    ["chinese"],
    "food",
    "Category fallback.",
    "generic",
  ),
  target(
    "food-healthy-assortment",
    "healthy vegan food assortment table",
    ["healthy", "vegan"],
    "food",
    "Category fallback.",
    "generic",
  ),
  target(
    "food-breakfast-assortment",
    "breakfast food assortment table",
    ["breakfast"],
    "food",
    "Category fallback.",
    "generic",
  ),
  target(
    "food-bakery-assortment",
    "artisan bakery bread pastry assortment",
    ["bakery"],
    "food",
    "Category fallback.",
    "generic",
  ),
  target(
    "food-dessert-assortment",
    "dessert assortment table",
    ["desserts"],
    "food",
    "Category fallback.",
    "generic",
  ),
  target(
    "grocery-pantry-assortment",
    "pantry staples grains unbranded",
    ["essentials", "quick meals", "pantry"],
    "grocery",
    "Category fallback.",
    "generic",
  ),
  target(
    "grocery-household-assortment",
    "household cleaning supplies unbranded",
    ["household"],
    "grocery",
    "Category fallback; avoid visible logos.",
    "generic",
  ),
  target(
    "grocery-personal-care-assortment",
    "personal care products unbranded",
    ["personal care"],
    "grocery",
    "Category fallback; avoid visible logos.",
    "generic",
  ),
];

export const pexelsTargets = [...exactTargets, ...categoryTargets];

const ids = new Set(pexelsTargets.map(({ id }) => id));
if (ids.size !== pexelsTargets.length)
  throw new Error("Duplicate Pexels target ID");
